services:
  - type: web
    name: bloom-api
    runtime: docker
    repo: https://github.com/walidabualafia/todo.js
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "8080"
      - key: DB_DRIVER
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: bloom-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: bloom-db
    plan: free
    databaseName: bloom
    user: bloom
