services:
  - type: web
    name: bloom-api
    runtime: docker
    repo: https://github.com/walidabualafia/todo.js
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "8080"
      - key: DB_DRIVER
        value: sqlite
      - key: DATABASE_URL
        value: /home/bloom/data/bloom.db
      - key: ENVIRONMENT
        value: production
      - key: JWT_SECRET
        generateValue: true
    disk:
      name: bloom-data
      mountPath: /home/bloom/data
      sizeGB: 1
